### PR TITLE
Fix project dir not found and copied

### PR DESCRIPTION
**Pull request by jopadan**
prefix COPY with GLOB_RECURSE

### CODE REVIEW

**Comment by encelo** [comment]
Hello @jopadan and thank you for taking interest in the project.
Can you explain to me why you prefixed `COPY`  with `GLOB_RECURSE`? What are you trying to fix?

If you read the CMake documentation for the [`file`](https://cmake.org/cmake/help/latest/command/file.html) command you can see that the `GLOB_RECURSE` sub-command generates a list of files and store it into a variable. It does not copy any files and it does not seem it can be used together with the `COPY` sub-command.

Have you tested your change? How does it differ from the original code?

**Comment by jopadan** [comment]
@encelo The file command doesn't find the empty directory and ignores subdirectories without adding the GLOB_RECURSE.
Applying the changes copies the directory recursively.
To reproduce run cmake . in source tree or in a separate out of source-tree build directory.

**Comment by encelo** [comment]
I cannot reproduce any issues you are describing: the current `COPY` command copies the whole `project` directory with everything in it, nothing is missing.
Instead, if I use `GLOB_RECURSE COPY` the command just fails and nothing gets copied. 😄
What platform are you on? What version of CMake?

**Comment by jopadan** [comment]
@encelo I am using linux-6.5.3 and cmake-3.27.5

**Comment by encelo** [comment]
You can't use `GLOB_RECURSE` and `COPY` together as they are two mutually exclusive sub-commands of `file()`.
Besides, `GLOB_RECURSE` is used to create a list of files. As a matter of fact, if I apply your change the copy is not performed anymore.

**Comment by encelo** [comment]
What's happening to you is very strange, have you tried debugging the CMake script step to step or with the new `--debugger` option?

Maybe adding `GLOB_RECURSE` just skip the copy and you do not encounter the error. As I said again, it's either the `GLOB_RECURSE` (that fills a variable with a list of files) or the `COPY` sub-command that you can use with `file()`.
About the `FOLLOW_SYMLINK_CHAIN` option, does it change anything in this case? There are no symlinks in the `project` directory. 🤔

I use Arch Linux as my main developing machine, currently with CMake 3.27.6. I have never had the problem you are describing with any versions of CMake I had since I introduced the `project` directory, neither on Linux nor on Windows. 🤷🏻‍♂️

Come on [Discord](https://discord.gg/495ab6Y) and we can have a chat about the issue. 👍🏻

**Pull request closed without merging**
